service: bgg
provider:
  name: aws
  region: eu-central-1
  runtime: python3.6
  environment:
    DB_USER: ${env:DB_USER}
    DB_NAME: ${env:DB_NAME}
    DB_PORT: ${env:DB_PORT}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_SCHEMA: ${env:DB_SCHEMA}
    DB_HOST: ${env:DB_HOST}

package:
  include:
    - launcher.py
    - bgg/**
    - scrapy.cfg
  exclude:
    - .circleci/**
    - .vscode/**
    - node_modules/**
    - venv/**
    - setup_env.sh
    - README.md
    - Pipfile
    - Pipfile.lock
    - package.json
    - package-lock.json
    - .gitignore
    - .flake8
    - .envrc

functions:
  scrape:
    handler: launcher.scrape


plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    slim: true
